services:
  gitlab:
    image: gitlab/gitlab-ce:18.4.2-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: 'mf1370p.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://mf1370p.local:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    logging:
        driver: "local"
        options:
            max-size: "10m"
    ports:
      - '8929:8929'
      - '8943:443'
      - '2424:22'
    volumes:
      - '$GITLAB_CONFIG_DIR:/etc/gitlab'
      - '$GITLAB_LOGS_DIR:/var/log/gitlab'
      - '$GITLAB_DATA_DIR:/var/opt/gitlab'
      - '$GITLAB_BACKUP_DIR:/backups/gitlab'
    shm_size: '512m'
